apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: instrumentation
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: web
  selector:
    prometheus: k8s
