apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
  namespace: instrumentation
spec:
  externalUrl: http://localhost:8001/api/v1/namespaces/instrumentation/services/prometheus-k8s/proxy/
  replicas: 3
  version: v1.7.0
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 3Gi
  alerting:
    alertmanagers:
    - namespace: instrumentation
      name: alertmanager-main
      port: web
