apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-event-metrics
  labels:
    k8s-app: kube-event-metrics
  namespace: instrumentation
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kube-event-metrics
  namespaceSelector:
    matchNames:
    - instrumentation
  endpoints:
  - port: http-metrics
    interval: 30s
    honorLabels: true
