apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: instrumentation
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    name: http
  selector:
    app: elasticsearch
