---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-event-metrics
    k8s-app: kube-event-metrics
  name: kube-event-metrics
  namespace: instrumentation
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app: kube-event-metrics
