---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-event-metrics
  namespace: instrumentation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-event-metrics
    spec:
      serviceAccountName: kube-event-metrics
      containers:
        - name: kube-event-metrics
          image: tommyvn/kube-event-metrics:v1.7.4-7
          ports:
            - name: metrics
              containerPort: 8080
              resources:
                requests:
                  memory: 100Mi
                  cpu: 100m
                limits:
                  memory: 100Mi
                  cpu: 100m
        - name: kubectl-proxy
          image: tommyvn/kubectl-proxy:v1.7.4-1
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 50m
