---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: instrumentation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:5.1.0
          command:
            - 'sh'
            - '-c'
            - '/run.sh'
          env:
            - name: GF_AUTH_BASIC_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-password
          volumeMounts:
            - name: grafana-config-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-config-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards-data
              mountPath: /var/lib/grafana/dashboards
          ports:
            - name: web
              containerPort: 3000
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: grafana-config-datasources
          configMap:
            name: grafana-config
            items:
              - key: datasources.yaml
                path: datasources.yaml
        - name: grafana-config-dashboards
          configMap:
            name: grafana-config
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
        - name: grafana-dashboards-data
          configMap:
            name: grafana-dashboards-data
