---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: instrumentation
data:
  datasources.yaml: |+
    apiVersion: 1
    # list of datasources to insert/update
    datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-k8s:9090
      access: proxy
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: false
  dashboards.yaml: |+
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 120 # how often Grafana will scan for changed dashboards
      options:
        path: /var/lib/grafana/dashboards
