---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube2iam
  labels:
    app: kube2iam
subjects:
  - kind: ServiceAccount
    name: kube2iam
    namespace: kube-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: kube2iam
  apiGroup: ""
