apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: instrumentation
  labels:
    app: elasticsearch
    elasticsearch-node-type: client
spec:
  ports:
  - port: 9200
    protocol: TCP
  selector:
    app: elasticsearch
    elasticsearch-node-type: client
