---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-curator
  namespace: instrumentation
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curator
              image: microdc/elasticsearch-curator:0.0.8
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/elasticsearch-curator
          volumes:
            - name: config-volume
              configMap:
                name: elasticsearch-curator
          restartPolicy: OnFailure
