---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-v1.23
  namespace: instrumentation
  labels:
    k8s-app: fluentd
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    version: v1.23
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd
        kubernetes.io/cluster-service: "true"
        version: v1.23
    spec:
      serviceAccountName: fluentd
      containers:
        - name: fluentd
          image: gcr.io/google_containers/fluentd-elasticsearch:1.23
          command:
            - '/bin/sh'
            - '-c'
            - '/usr/sbin/td-agent $FLUENTD_ARGS'
          env:
            - name: FLUENTD_ARGS
              value: -q
            - name: FLUENTD_ELASTICSEARCH_HOST
              value: "elasticsearch"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
      tolerations:
        - effect: NoSchedule
          operator: Exists
