---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
    k8s-app: alertmanager
  name: alertmanager-main
  namespace: instrumentation
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: main
