---
kind: Service
apiVersion: v1
metadata:
  name: nginx-default-backend
  namespace: kube-ingress
  labels:
    k8s-app: default-http-backend
    k8s-addon: nginx-ingress.addons.k8s.io
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: nginx-default-backend
