apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Alertmanager"
metadata:
  name: "main"
  labels:
    alertmanager: "main"
  namespace: instrumentation
spec:
  externalUrl: http://localhost:8001/api/v1/namespaces/instrumentation/services/alertmanager-main/proxy/
  replicas: 3
  version: v0.7.1
